### PR TITLE
README updated #27

### LINKED ISSUE #27: Extend README file
**Is your feature request related to a problem? Please describe.**

From selling and marketing point of view, it would be nice to extend the current README file and provide some examples how to install and run this tool. Examples with a real-world usage would be appropriate for new comers.

### PR DESCRIPTION
**Pull request by tushar7sharma**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [ ] No

## This Pull Request implements

… Explain your changes.

### CODE REVIEW

**Comment by harshad16** [comment]
can you please rebase, there are 29 commits but only one file is changed.

**Comment by tushar7sharma** [comment]
> can you please rebase, there are 29 commits but only one file is changed.

I tried doing a rebase but I'm getting conflicts in all files. Maybe because branches have already been merged?
Anyways, even if the PR is showing a diff of 29 commits, only a single commit will get pushed to the upstream repo.

**Comment by harshad16** [comment]
> > can you please rebase, there are 29 commits but only one file is changed.
> 
> I tried doing a rebase but I'm getting conflicts in all files. Maybe because branches have already been merged?
> Anyways, even if the PR is showing a diff of 29 commits, only a single commit will get pushed to the upstream repo.

probably, okay 
I was just intrigued with those commits compared to change.

**Review by fridex — APPROVED** [review]
:+1: 

Maybe an example of classification would be great to state verbatim in the text (so I don't need to install the tool to see how it works). Also, a link to Kebechet's version manager would be great so we see integration in action ([a link to manager](https://github.com/thoth-station/kebechet/tree/master/kebechet/managers/version
) and a link to automatically generated changelog to isee it in action).

**Pull request merged**
